apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2-container
        image: thebluedrara/apache2-image:latest
        ports:
        - containerPort: 80

# spec: the specs of the deployment
# replicas: the amount of identical pods it will create
